// <auto-generated />
namespace WebUmea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class NewModels_Uncertainty_Contribution_Pdfs01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewModels_Uncertainty_Contribution_Pdfs01));
        
        string IMigrationMetadata.Id
        {
            get { return "202002071201067_NewModels_Uncertainty_Contribution_Pdfs01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
